dist: trusty
sudo: required
language: rust
rust:
 - stable
cache:
directories:
- $HOME/.cargo

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_install:

  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.10.0/cassandra-cpp-driver-dbg_2.10.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.10.0/cassandra-cpp-driver-dev_2.10.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.10.0/cassandra-cpp-driver_2.10.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.23.0/libuv1-dbg_1.23.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.23.0/libuv1-dev_1.23.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.23.0/libuv1_1.23.0-1_amd64.deb
  - sudo dpkg -i libuv1-dbg_1.23.0-1_amd64.deb libuv1-dev_1.23.0-1_amd64.deb  libuv1_1.23.0-1_amd64.deb cassandra-cpp-driver_2.10.0-1_amd64.deb cassandra-cpp-driver-dbg_2.10.0-1_amd64.deb cassandra-cpp-driver-dev_2.10.0-1_amd64.deb

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:/usr/local/bin:$PATH

# Enforce that all new commits are signed off according to the DCO,
# per CONTRIBUTING.md. Prior commits are either pre-fork, are signed off,
# or were made by Keith Wansbrough, who hereby certifies the DCO with regard
# to each such commit.
#
# We then build all the code, then test it.
script:
- |
  DCO_SIGNING_BASE_COMMIT=f43fa8aeac397cfbd4a470f506581948e807013c &&
  if git log ${DCO_SIGNING_BASE_COMMIT}.. --grep "^signed-off-by: .\+@.\+" --regexp-ignore-case --invert-grep --no-merges | grep ^ ;
  then echo '**One or more commits are not signed off!' ; /bin/false ; fi &&
  cargo build &&
  cargo test

after_success:
- travis-cargo coveralls --no-sudo
